---
- name: This play ensures prerequisites are satisfied before installing
  hosts: vm_host
  vars_files:
    - vars/cluster_vars.yml
    - vars/infra_vars.yml
  tasks:

    - name: Check if distribution is supported
      fail:
        msg: Your distribution is actually unsupported
      when:
        - ansible_distribution != 'CentOS'
        - ansible_distribution_major_version | int < 7

    - name: Check if distribution is supported
      fail:
        msg: Your distribution is actually unsupported
      when:
        - ansible_distribution != 'Fedora'    
    
    - name: Block of cluster checks
      block:
        - fail: 
            msg: "Only ONE bootstrap node can be present"
          when: cluster_nodes.host_list.bootstrap | count > 1

        - fail:
            msg: 'To provision NO workers, you must flag "three_node" varible to true in vars/cluster_vars.yml'
          when: 
            - ( cluster_nodes.host_list.workers | count <= 0 )
            - not three_node
  
        - fail: 
            msg: "Please check the host_list variable in cluster_nodes"
          when: ( cluster_nodes.host_list.masters | count <= 0 ) or ( cluster_nodes.host_list.workers | count <= 0 ) or ( cluster_nodes.host_list.bootstrap | count <= 0 )
      
        - name: Fail fast if bootstrap node doesn't meet minimum requirements
          fail:
            msg: "Bootstrap nodes must be provisioned with at least 16GB memory, 40GB storage and 4vCPUs"
          when: ( cluster_nodes.specs.bootstrap.vcpu < 4 ) or ( cluster_nodes.specs.bootstrap.mem < 16 ) or ( cluster_nodes.specs.bootstrap.disk < 40 )
        
        - name: Fail fast if master nodes don't meet minimum requirements               
          fail:                                                                             
            msg: "Master nodes must be provisioned with at least 16GB memory, 40GB storage and 4vCPUs"
          when: ( cluster_nodes.specs.masters.vcpu < 4 ) or ( cluster_nodes.specs.masters.mem < 16 ) or ( cluster_nodes.specs.masters.disk < 40 )
           
        - name: Fail fast if worker nodes don't meet minimum requirements
          fail:                                                                             
            msg: "Worker nodes must be provisioned with at least 8GB memory and 2vCPUs"
          when: ( cluster_nodes.specs.workers.vcpu < 2 ) or ( cluster_nodes.specs.workers.mem < 8 ) or ( cluster_nodes.specs.workers.disk < 40 )

        - name: Check for pullSecret variable and fail fast
          fail:
            msg: "Check the pullSecret var in files/vars.yaml"
          when: (cluster.pullSecret is undefined) or (cluster.pullSecret | length < 1)
    
    - name: Block of infra checks
      block:
        - fail:
            msg: "At least one bastion and one loadbalancer VMs must be created"
          when: ( infra_nodes.host_list.bastion | count != 1 or infra_nodes.host_list.loadbalancer | count != 1 )
      


