---
- name: This play installs needed tools to provision infrastructure VMs
  hosts: vm_host
  vars_files:
    - vars/libvirt.yml
  tasks:

    - name: Install needed packages
      yum:
        name: "{{ virtualization_packages.centos8 }}"
        state: latest
      become: true
      when:
        - ansible_distribution == 'CentOS'
        - ansible_distribution_major_version | int == 8

    - name: Install needed packages
      yum:
        name: "{{ virtualization_packages.centos7 }}"
        state: latest
      become: true
      when:
        - ansible_distribution == 'CentOS'
        - ansible_distribution_major_version | int == 7

    - name: Install needed packages
      yum:
        name: "{{ virtualization_packages.fedora }}"
        state: latest
      become: true
      when:
        - ansible_distribution == 'Fedora'

    - name: Download and provision Terraform
      unarchive:
        src: "{{ terraform_release_url }}"
        dest: /usr/bin/
        mode: 755
        remote_src: yes
      become: true


    - name: Virtualization services are enabled
      service:
        name: libvirtd
        state: started
        enabled: true
      become: true

    - git:
        repo: "{{ terraform_libvirt_provider_url }}"
        dest: "{{ terraform_libivrt_provider_folder }}"
        force: true

    - name: Run 'install' target on libivrt-provider
      make:
        chdir: "{{ terraform_libivrt_provider_folder }}"
        target: install

    - name: Ensures terraform plugins directory exists
      file:
        path: "{{ terraform_plugin_dir }}"
        state: directory
        mode: 0744

    - name: Copy libvirt provider to plugins directory
      copy:
        src: "{{ gopath }}/bin/terraform-provider-libvirt"
        dest: "{{ terraform_plugin_dir }}"
        remote_src: true
        mode: 0755

    - name: Ensure pool path exists
      file:
        path: "{{ libvirt.storage.pool_path }}"
        state: directory
      become: true

    - name: Define libvirt network
      virt_net:
        command: define
        name: "{{ libvirt.network.network_name }}"
        xml: '{{ lookup("template", "templates/libvirt_network.xml.j2") }}'

    - name: Make libvirt network autostart
      virt_net:
        name: "{{ libvirt.network.network_name }}"
        autostart: true

    - name: Start libvirt network
      virt_net:
        command: start
        name: "{{ libvirt.network.network_name }}"
        state: active

    - name: Define libvirt pool
      virt_pool:
        command: define
        name: "{{ libvirt.storage.pool_name }}"
        xml: '{{ lookup("template", "templates/libvirt_pool.xml.j2") }}'

    - name: Make libvirt pool autostart
      virt_pool:
        name: "{{ libvirt.storage.pool_name }}"
        autostart: true

    - name: Start libvirt pool
      virt_pool:
        command: start
        name: "{{ libvirt.storage.pool_name }}"
        state: active
